[settings]
timeout = 1000

[relaychain]
default_image = "{{ZOMBIENET_INTEGRATION_TEST_IMAGE}}"
chain = "rococo-local"
command = "polkadot"

  [[relaychain.nodes]]
  name = "alice"
  extra_args = [ "--alice" ]

  [[relaychain.nodes.env]]
  name = "RUST_LOG"
  value = "parachain=debug"

#  [[relaychain.nodes.overrides]]
#  local_path = "../../target/release/polkadot"
#  remote_name = "wonderland"

  [[relaychain.nodes]]
  name = "bob"
  extra_args = [ "--bob" ]

  [[relaychain.nodes.env]]
  name = "RUST_LOG"
  value = "parachain=debug"

#  [[relaychain.nodes.overrides]]
#  local_path = "../../target/release/polkadot"
#  remote_name = "builder"

[[parachains]]
id = 100
addToGenesis = false

  [parachains.collator]
  name = "collator01"
  image = "{{COL_IMAGE}}"
  command = "/usr/local/bin/adder-collator"

[types.Header]
number = "u64"
parent_hash = "Hash"
post_state = "Hash"
